version: "3.7"
services:
  discovery-service:
    image: discovery-service
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - users-network


  authorization-service:
    image: authorization-service
    build:
      context: authorizationService
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:9095/eureka
    ports:
      - "9095:9095"
    restart: always
    depends_on:
      - discovery-service
    networks:
      - users-network

  calculate-networth:
    image: calculate-networth
    build:
      context: calculateNetworth
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:9003/eureka
    depends_on:
      - discovery-service
      - daily-mutual-fund-nav
      - daily-share-price
    networks:
      - users-network

  daily-mutual-fund-nav:
    image: daily-mutual-fund-nav
    build:
      context: DailyMutualFundNAV
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:9002/eureka
    depends_on:
      - discovery-service
    networks:
      - users-network

  daily-share-price:
    image: daily-share-price
    build:
        context: DailySharePrice
        dockerfile: Dockerfile
    ports:
        - "9001:9001"
    restart: always
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:9001/eureka
    depends_on:
        - discovery-service
    networks:
        - users-network
    

  view-controller:
    image: view-controller
    build:
      context: viewController
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - authorization-service
      - calculate-networth
    networks:
      - users-network

# Networks to be created to facilitate communication between containers
networks:
  users-network:
